<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_obat_alkes_bhp_model extends CI_Model
{

    public $table = 'tbl_obat_alkes_bhp';
    public $id = 'kode_barang';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kode_barang', $q);
	$this->db->or_like('nama_barang', $q);
	$this->db->or_like('id_kategori_barang', $q);
	$this->db->or_like('id_satuan_barang', $q);
	$this->db->or_like('harga', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('tbl_obat_alkes_bhp.kode_barang', $q);
	$this->db->or_like('tbl_obat_alkes_bhp.nama_barang', $q);
	$this->db->or_like('tbl_obat_alkes_bhp.id_kategori_barang', $q);
	$this->db->or_like('tbl_obat_alkes_bhp.id_satuan_barang', $q);
	$this->db->or_like('tbl_obat_alkes_bhp.harga', $q);
        $this->db->join('tbl_kategori_barang','tbl_kategori_barang.id_kategori_barang=tbl_obat_alkes_bhp.id_kategori_barang');
        $this->db->join('tbl_satuan_barang','tbl_satuan_barang.id_satuan=tbl_obat_alkes_bhp.id_satuan_barang');
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_obat_alkes_bhp_model.php */
/* Location: ./application/models/Tbl_obat_alkes_bhp_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-09 11:24:01 */
/* http://harviacode.com */